name: CI - Build, Scan, and Push Docker

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-scan-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

     

      # 3. SonarQube Scan
      - name: Debug SonarQube URL
        run: echo "Using SonarQube at ${{ secrets.SONAR_HOST_URL }}"

      - name: SonarQube Scan
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
              -Dsonar.projectKey=web-calci \
              -Dsonar.host.url=http://51.20.190.39:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}


      # 4. Build with Maven (after scan)
      - name: Build with Maven
        run: mvn -B -ntp package

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build & push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/web-calci
          
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .
          
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
